### ISSUE TITLE
Another gsub does not work on URL issue

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-client-ruby#116]
See https://github.com/hawkular/hawkular-client-ruby/blob/master/lib/hawkular/hawkular_client.rb#L61

```
  Operations::OperationsClient.new(entrypoint: @state[:entrypoint].gsub(/^https?/, 'ws'),
```

**Comment by abonas** [comment]
can you be a bit more specific what is the problem? the title is quite vague, I am kind of guessing what is not working :) 
another gsub in addition to what? does not work in which way?

**Comment by abonas** [comment]
regardless, do you know why `gsub` is used and not `sub`? (the latter is faster, it replaces the first occurence of the needed substring only, which in this case of protocol is reasonable)

**Comment by rubenvp8510** [comment]
I think this issue is the same we had on URL normalization method https://github.com/hawkular/hawkular-client-ruby/pull/107  when we assume the entry point is a string, but it can be a URI object also.

Is this the same case?  @pilhuhn

**Comment by pilhuhn** [comment]
On 18 Jul 2016, at 18:47, Ruben Vargas wrote:

> I think this issue is the same we had on URL normalization method[1] 
> when we assume the entry point is a string, but it can be a URI object 
> also.
> 
> Is this the same case?  @pilhuhn

Yes

**Comment by abonas** [comment]
lets say we've received here a URI. I am not sure whether uri object works at all with ws. 
meaning - the user was able to actually create a uri object intended for operation with websockets?

**Comment by pilhuhn** [comment]
This happens when you go

```
uri = URI.parse('http://..')
hash = { entrypoint: uri, ... }
client=Hawkular::Client.new(hash)
ops = client.operations
```

I think it is enough to modify

`Operations::OperationsClient.new(entrypoint: @state[:entrypoint].gsub(/^https?/, 'ws'),`

to

`Operations::OperationsClient.new(entrypoint: @state[:entrypoint].to_s.sub(/^https?/, 'ws'),`

We need to revisit the whole WS handling once we allow for SSL, which we don't do yet (then the operations client also needs more code internally iirc).

**Comment by abonas** [comment]
I understand when it can happen code wise if you initialize the "base" client - and indeed the above example would solve it. But iiic users can also initialize directly the subclients, and then how would that be handled for operations/ws if URI is passed? (my point is that if operations client works only with websockets, supporting accepting an URI object here if it can't represent ws is incorrect in the first place. clearly it can be solved in code)
Also the above code subs `https` for `ws`, but you wrote that SSL is not allowed, that part confuses me :confused:

**Comment by pilhuhn** [comment]
On 19 Jul 2016, at 10:48, abonas wrote:

> I understand when it can happen code wise if you initialize the "base" 
> client - and indeed the above example would solve it. But iiic users 
> can also initialize directly the subclients, and then how would that 
> be handled for operations if URI is passed?

Yes, for a direct call into the subclient, it would also need a .to_s
in its `uri = URI.parse ep` line. Usually except for metrics-only 
operation
of CM, people don't call the sub-clients without the parent.
We should make that more explicit / prominent though.

> Also the above code subs `https` for `ws`, but you wrote that SSL is 
> not allowed, that part confuses me :confused:

the `https?` regex allows for both `http` and `https` - I think that is 
ok.
We catch both and then use a `ws:uri`.
