### ISSUE TITLE
Add an option to query metrics based on tag only (regardless to type)

### ISSUE THREAD

**Issue by alongoldboim** [hawkular/hawkular-client-ruby#175]
```ruby
Hawkular::Metrics::Client.new(entrypoint, credentials, options).strings.get_data_by_tags(:miq_metric => true)
```

will work, but i need it to work without the strings section.
cc @pilhuhn @zgalor @simon3z.

**Comment by alongoldboim** [comment]
@pilhuhn @zgalor @simon3z

**Comment by pilhuhn** [comment]
@rubenvp8510 Can you have a look at this? @burmanm says that this is possible in hawkular-metrics.

**Comment by alongoldboim** [comment]
cc @simon3z @zgalor
