### ISSUE TITLE
Support for multi-tenant operations

### ISSUE THREAD

**Issue by moolitayer** [hawkular/hawkular-client-ruby#176]
There are going to be cross tenant apis for alerting e.g get alerts for all tenants. 
We would need to have some support for those in clients, currently created with one tenant in mind.

**Comment by moolitayer** [comment]
cc @lucasponce

**Comment by josejulio** [comment]
Could you elaborate a bit more?

**Comment by moolitayer** [comment]
Wow that's quick, just discussed in a meeting with @lucasponce and @rubenvp8510 added description.

**Comment by lucasponce** [comment]
The endpoints would need support from client are these ones:
http://www.hawkular.org/docs/rest/rest-alerts.html#__admin_cross_tenant_operations

**Comment by moolitayer** [comment]
Specifically, the endpoint I'm using is:

```
curl -k -s \
    -H "Hawkular-Tenant: _system" \
    -H "Authorization: Bearer $HAWKULAR_TOKEN" \
    https://$HAWKULAR_HOST/hawkular/alerts/admin/alerts 
```

**Comment by lucasponce** [comment]
@josejulio @rubenvp8510 could you take a look to this one ?
