### ISSUE TITLE
Incompatible with rest-client 2.1.0.rc1 ?

### ISSUE THREAD

**Issue by cben** [hawkular/hawkular-client-ruby#230]
Heads up, tests fail with upcoming rest-client 2.1.0.rc1.,

- [ ] strange error (the strange char is 0x1F "UNIT SEPARATOR").
  ```
  HawkularClient and Metrics client Should both return the version
  Failure/Error: res.empty? ? {} : JSON.parse(res)

  JSON::ParserError:
    784: unexpected token at ''
  # ./lib/hawkular/base_client.rb:39:in `http_get'
  # ./lib/hawkular/metrics/metric_api.rb:38:in `fetch_version_and_status'
  # ./spec/integration/hawkular_client_spec.rb:214:in `block (4 levels) in <module:RSpec>'
  ```
  (I also saw this with in manageiq-providers-kubernetes tests, some hawkular-client related tests gave this.)

- [ ] lots of VCR::Errors::UnhandledHTTPRequestError

**Comment by abonas** [comment]
@cfcosta please have a look

**Comment by abonas** [comment]
@cben thank you for the heads up
