### ISSUE TITLE
Move the HawkularUtilsMixin under the Hawkular module

### ISSUE THREAD

**Issue by jkremser** [hawkular/hawkular-client-ruby#78]
`::HawkularUtilsMixin` -> `::Hawkular::HawkularUtilsMixin`

**Comment by josejulio** [comment]
This is done in https://github.com/hawkular/hawkular-client-ruby/pull/184/commits/6308f477ad8273b4ac096e3189ec063875943269 and marked as deprecated in https://github.com/hawkular/hawkular-client-ruby/pull/194/commits/bfdcf48c310d61191fa14dc0ffbf53f199d8f214
