### ISSUE TITLE
Availability endpoint get_data has no 'distinct' parameter

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-client-ruby#92]
Availability has a parameter to only return distinct values 
See https://github.com/hawkular/hawkular-metrics/blob/0.8.2/api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/AvailabilityHandler.java#L243

this should be reflected in the availability part of metrics-sub-client

Also it has no percentiles.

// cc @simon3z

**Comment by simon3z** [comment]
cc @yaacov

**Comment by pilhuhn** [comment]
See also https://issues.jboss.org/browse/HWKMETRICS-428
